// <auto-generated />
using System;
using HotelManagement.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace HotelManagement.Migrations
{
    [DbContext(typeof(AsyncInnDbContext))]
    [Migration("20220424120856_update-RoomAmenities-model")]
    partial class updateRoomAmenitiesmodel
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.16")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("HotelManagement.Models.Amenity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Amenities");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Personal care"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Coffee Kit"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Tissue box"
                        });
                });

            modelBuilder.Entity("HotelManagement.Models.Hotel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Phone")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.ToTable("Hotels");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "Amman",
                            Name = "Life Hotel",
                            Phone = 782625620.0
                        },
                        new
                        {
                            Id = 2,
                            Address = "Irbid",
                            Name = "7Star Hotel",
                            Phone = 797645630.0
                        },
                        new
                        {
                            Id = 3,
                            Address = "Aqaba",
                            Name = "Mina Hotel",
                            Phone = 868763450.0
                        });
                });

            modelBuilder.Entity("HotelManagement.Models.HotelRoom", b =>
                {
                    b.Property<int>("HotelId")
                        .HasColumnType("int");

                    b.Property<int>("RoomNumber")
                        .HasColumnType("int");

                    b.Property<bool>("PetFriendly")
                        .HasColumnType("bit");

                    b.Property<decimal>("Rate")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("RoomID")
                        .HasColumnType("int");

                    b.HasKey("HotelId", "RoomNumber");

                    b.HasIndex("RoomID");

                    b.ToTable("HotelRoom");
                });

            modelBuilder.Entity("HotelManagement.Models.Room", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Layout")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Rooms");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Layout = "A room assigned to one person. May have one or more beds.",
                            Name = "Single"
                        },
                        new
                        {
                            Id = 2,
                            Layout = "A room assigned to two people. May have one or more beds.",
                            Name = "Double"
                        },
                        new
                        {
                            Id = 3,
                            Layout = "A room assigned to three people. May have two or more beds.",
                            Name = "Triple"
                        });
                });

            modelBuilder.Entity("HotelManagement.Models.RoomAmenities", b =>
                {
                    b.Property<int>("RoomID")
                        .HasColumnType("int");

                    b.Property<int>("AmenitiesId")
                        .HasColumnType("int");

                    b.Property<int?>("amenityId")
                        .HasColumnType("int");

                    b.HasKey("RoomID", "AmenitiesId");

                    b.HasIndex("amenityId");

                    b.ToTable("RoomAmenities");
                });

            modelBuilder.Entity("HotelManagement.Models.HotelRoom", b =>
                {
                    b.HasOne("HotelManagement.Models.Hotel", "hotel")
                        .WithMany("hotel")
                        .HasForeignKey("HotelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HotelManagement.Models.Room", "room")
                        .WithMany("room")
                        .HasForeignKey("RoomID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("hotel");

                    b.Navigation("room");
                });

            modelBuilder.Entity("HotelManagement.Models.RoomAmenities", b =>
                {
                    b.HasOne("HotelManagement.Models.Room", "room")
                        .WithMany("roomamenity")
                        .HasForeignKey("RoomID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HotelManagement.Models.Amenity", "amenity")
                        .WithMany("amenity")
                        .HasForeignKey("amenityId");

                    b.Navigation("amenity");

                    b.Navigation("room");
                });

            modelBuilder.Entity("HotelManagement.Models.Amenity", b =>
                {
                    b.Navigation("amenity");
                });

            modelBuilder.Entity("HotelManagement.Models.Hotel", b =>
                {
                    b.Navigation("hotel");
                });

            modelBuilder.Entity("HotelManagement.Models.Room", b =>
                {
                    b.Navigation("room");

                    b.Navigation("roomamenity");
                });
#pragma warning restore 612, 618
        }
    }
}
